--Insert Movies 
INSERT INTO movies (title, genre, release_year, director, rating, imdb_rating, duration_minutes) 
VALUES 
('The Avengers', 'Action', 2012, 'Joss Whedon', 'PG-13', 8.0, 143),
('Inception', 'Sci-Fi', 2010, 'Christopher Nolan', 'PG-13', 8.8, 148), 
('Titanic', 'Romance', 1997, 'James Cameron', 'PG-13', 8.0, 195), 
('Harry Potter and the Sorcers Stone', 'Fantasy', 2001, 'Chris Columbus', 'PG', 7.7, 152),
('Pirates of the Caribebean: The Curse of the Black Pearl', 'Action', 2003, 'Gore Verbinski', 'PG-13', 8.1, 143),
('Step Brothers', 'Comedy', 2008, 'Adam McKay', 'R', 6.9, 98), 
('The Dark Knight', 'Action', 2008, 'Christopher Nolan', 'PG-13', 9.1, 152), 
('The Lion King', 'Animation', 1994, 'Roger Allers', 'G', 8.5, 88), 
('Schindlers List', 'History', 1993, 'Steven Spielberg', 'R', 9.0, 195),  
('The Shawshank Redemption', 'Drama', 1994, 'Frank Darabont', 'R', 9.3, 142), 
('The Devil Wears Prada 2', 'Satire', 2026, 'David Frankel', 'PG-13', 6.8, 119), 
('The Godfather', 'Drama', 1972, 'Francis Ford Coppola', 'R', 9.2, 175), 
('Forest Gump', 'Drama', 1994, 'Robert Zemeckis', 'PG-13', 8.8, 142), 
('Saving Private Ryan', 'Action', 1998, 'Steven Spielberg', 'R', 8.6, 169), 
('Toy Story', 'Animation', 1995, 'John Lasseter', 'G', 8.3, 81), 
('Braveheart', 'Drama', 1995, 'Mel Gibson', 'R', 8.3, 178), 
('Star Wars: Episode V - The Empire Strikes Back', 'Sci-Fi', 1980, 'Irvin Kershner', 'PG', 8.7, 124), 
('Back to the Future', 'Sci-Fi', 1985, 'Robert Zemeckis', 'PG', 8.5, 116), 
('The Sound of Music', 'Musical', 1965, 'Robert Wise', 'G', 8.1, 174),
('Scarface', 'Crime', 1983, 'Brian De Palma', 'R', 8.3, 170);  

--Insert Actors
INSERT INTO actors (movie_id, first_name, last_name, character_name, gender) 
VALUES
(1, 'Robert', 'Downey Jr.', 'Iron Man', 'Male'),
(1, 'Chris', 'Evans', 'Captian America', 'Male'),
(1, 'Mark', 'Ruffalo', 'Hulk', 'Male'),
(1, 'Chris', 'Hemsworth', 'Thor', 'Male'), 
(1, 'Scarlett', 'Johansson', 'Black Widow', 'Female'), 
(2, 'Leonardo', 'DiCaprio', 'Cobb', 'Male'),
(2, 'Tom', 'Hardy', 'Eames', 'Male'),
(2, 'Cillian', 'Murphy', 'Robert Fischer Jr.', 'Male'),  
(2, 'Joseph', 'Gordan-Levitt', 'Arthur', 'Male'), 
(3, 'Leonardo', 'DiCaprio', 'Jack Dawson', 'Male'), 
(3, 'Kate', 'Winslet', 'Rose DeWitt Bukater', 'Female'),
(3, 'Billy', 'Zane', 'Cal Hockley', 'Male'), 
(3, 'Kathy', 'Bates', 'Molly Brown', 'Female'), 
(3, 'Bernard', 'Hill', 'Captain Smith', 'Male'),
(4, 'Daniel', 'Radcliffe', 'Harry Potter', 'Male'),
(4, 'Rupert', 'Grint', 'Ron Weasley', 'Male'),
(4, 'Eamma', 'Watson', 'Hermione Granger', 'Female'),
(4, 'Ricahrd', 'Harris', 'Albus Dumbledore', 'Male'), 
(4, 'Robbie', 'Coltrane', 'Hagrid', 'Male'), 
(5, 'Johnny', 'Depp', 'Captain Jack Sparrow', 'Male'), 
(5, 'Orlando', 'Bloom', 'Will Turner', 'Male'), 
(5, 'Keira', 'Knightley', 'Elizabeth Swann', 'Female'), 
(5, 'Geoffrey', 'Rush', 'Barbossa', 'Male'), 
(5, 'Jonathan', 'Pryce', 'Governor Weatherby Swann', 'Male'), 
(6, 'Will', 'Ferrell', 'Brennan Huff', 'Male'), 
(6, 'John', 'C. Reilly', 'Dale Doback', 'Male'), 
(6, 'Mary', 'Steenburgen', 'Nancy Huff', 'Female'), 
(6, 'Richard', 'Jenkins', 'Dr. Robert Doback', 'Male'), 
(6, 'Adam', 'Scott', 'Derek', 'Male'), 
(7, 'Chrstian', 'Bale', 'Batman', 'Male'), 
(7, 'Heath', 'Ledger', 'Joker', 'Male'), 
(7, 'Aaron', 'Eckhart', 'Harvey Dent', 'Male'), 
(7, 'Cillian', 'Murphy', 'Scarecrow', 'Male'), 
(7, 'Morgan', 'Freeman', 'Lucius Fox', 'Male'), 
(7, 'Michael', 'Caine', 'Alfred', 'Male'), 
(8, 'James', 'Earl Jones', 'Mufassa(Voice)', 'Male'), 
(8, 'Matthew', 'Broderick', 'Simba(Voice)', 'Male'), 
(8, 'Jeremy', 'Irons', 'Scar(Voice)', 'Male'), 
(8, 'Whoopi', 'Goldberg', 'Shenzi(Voice)', 'Female'), 
(8, 'Robert', 'Guillaume', 'Rafiki(Voice)', 'Male'), 
(8, 'Moira', 'Kelly', 'Nala(Voice)', 'Female'), 
(8, 'Frank', 'Welker', 'Lion Roars(Voice)', 'Male'), 
(9, 'Liam', 'Neeson', 'Oskar Schindler', 'Male'), 
(9, 'Ben', 'Kingsley', 'Itzhak Stern', 'Male'), 
(9, 'Caroline', 'Goodall', 'Emilie Schindler', 'Female'), 
(9, 'Ralph', 'Fiennes', 'Amon Goeth', 'Male'), 
(9, 'Embeth', 'Davidtz', 'Helen Hirsch', 'Female'), 
(10, 'Bob', 'Gunton', 'Warden Norton', 'Male'),
(10, 'Tim', 'Robbins', 'Andy Dufresne', 'Male'),
(10, 'Morgan', 'Freeman', 'Ellis Boyd Redding (Red)', 'Male'), 
(10, 'William', 'Sadler', 'Heywood', 'Male'), 
(10, 'Clancy', 'Brown', 'Captain Hadley', 'Male'), 
(11, 'Meryl', 'Streep', 'Miranda', 'Female'), 
(11, 'Anne', 'Hathaway', 'Andy', 'Female'), 
(11, 'Emily', 'Blunt', 'Emily', 'Female'), 
(11, 'Stanley', 'Tucci', 'Nigel', 'Male'), 
(12, 'Al', 'Pacino', 'Michael Corleone', 'Male'), 
(12, 'Marlon', 'Brando', 'Don Vito Corleone', 'Male'), 
(12, 'James', 'Caan', 'Sonny Corleone', 'Male'), 
(12, 'Diane', 'Keaton', 'Kay Adams Corleone', 'Female'), 
(12, 'Robert', 'Duvall', 'Tom Hagen', 'Male'), 
(12, 'Richard', 'S. Castellano', 'Peter Clemenza', 'Male'), 
(13, 'Tom', 'Hanks', 'Forrest Gump', 'Male'), 
(13, 'Robin', 'Wright', 'Jenny Curran', 'Female'),
(13, 'Gary', 'Sinise', 'Lt. Dan Taylor', 'Male'), 
(13, 'Sally', 'Field', 'Mrs.Gump', 'Female'), 
(14, 'Tom', 'Hanks', 'Captain Miller', 'Male'), 
(14, 'Matt', 'Damon', 'Private Ryan', 'Male'), 
(14, 'Vin', 'Diesel', 'Private Caparzo', 'Male'), 
(14, 'Ted', 'Danson', 'Captain Hamill', 'Male'), 
(14, 'Tom', 'Sizemore', 'Sergeant Horvath', 'Male'), 
(14, 'Paul', 'Giamatti', 'Sergeant Hill', 'Male'), 
(14, 'Adam', 'Goldberg', 'Private Mellish', 'Male'), 
(15, 'Tom', 'Hanks', 'Woody(voice)', 'Male'), 
(15, 'Tim', 'Allen', 'Buzz Lightyear(voice)', 'Male'), 
(15, 'Don', 'Rickles', 'Mr.Potato Head(voice)', 'Male'), 
(15, 'John', 'Morris', 'Andy(voice)', 'Male'), 
(15, 'Wallace', 'Shawn', 'Rex(voice)', 'Male'), 
(15, 'Annie', 'Potts', 'Bo Peep(voice)', 'Female'), 
(16, 'Mel', 'Gibson', 'William Wallace', 'Male'), 
(16, 'Sophie', 'Marceau', 'Princess Isabelle', 'Female'), 
(16, 'Patrick', 'McGoohan', 'King Edward I', 'Male'), 
(16, 'Sandy', 'Nelson', 'John Wallace', 'Male'), 
(17, 'Mark', 'Hamill', 'Luke Skywalker', 'Male'), 
(17, 'Harrison', 'Ford', 'Han Solo', 'Male'), 
(17, 'Carrie', 'Fisher', 'Princess Leia', 'Female'), 
(17, 'David', 'Powers', 'Darth Vader', 'Male'), 
(17, 'Peter', 'Mayhew', 'Chewbacca', 'Male'), 
(17, 'Frank', 'Oz', 'Yoda(voice)', 'Male'), 
(17, 'Alec', 'Guinness', 'Obi-Wan Kenobi', 'Male'), 
(18, 'Michael', 'Fox J.', 'Marty McFly', 'Male'), 
(18, 'Christopher', 'Lloyd', 'Dr. Emmett Brown', 'Male'), 
(18, 'Crispin', 'Glover', 'George McFly', 'Male'), 
(18, 'Lea', 'Thompson', 'Lorraine Baines', 'Female'),
(18, 'Claudia', 'Wells', 'Jennifer Parker', 'Female'), 
(18, 'Marc', 'McClure', 'Dave McFly', 'Male'), 
(18, 'Wendie', 'Jo Sperber', 'Linda McFly', 'Female'), 
(19, 'Julie', 'Andrews', 'Maria', 'Female'), 
(19, 'Eleanor', 'Parker', 'The Baroness', 'Female'), 
(19, 'Christopher', 'Plummer', 'Captain Georg von Trapp', 'Male'), 
(19, 'Richard', 'Haydn', 'Max Detweiler', 'Male'), 
(19, 'Peggy', 'Wood', 'Mother Abess', 'Female'), 
(20, 'Al', 'Pacino', 'Tony Montana', 'Male'), 
(20, 'Michelle', 'Pfeiffer', 'Elvira', 'Female'), 
(20, 'Steven', 'Bauer', 'Manny Ray', 'Male'),
(20, 'Mary', 'Elizabeth Masstrantonio', 'Gina', 'Female'), 
(20, 'Miriam', 'Colon', 'Mama Montana', 'Female'),
(20, 'Paul', 'Shenar', 'Alejandro Sosa', 'Male'),
(20, 'Robert', 'Loggia', 'Frank Lopez', 'Male'); 



